In [1]:
import numpy as np
import pandas as pd

## Data Types & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

## Dot Products example

In [4]:
np.random.seed(0)
sales_amounts = np.random.randint(20,size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [5]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index = ['Mon','Tue','Wed','Thurs','Fri'],
                            columns=['Almond butter','Peanut Butter','Cashew Butter'])
weekly_sales
                    

Almond butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [6]:
# Create prices array
prices = np.array([10,8,12])
prices = prices.reshape(1,3)
prices

array([[10,  8, 12]])

In [7]:
#Create butter prices DataFrame
butter_prices = pd.DataFrame(prices,
                            index=['Price'],
                            columns=['Almond butter','Peanut Butter','Cashew Butter'])
butter_prices

Almond butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [8]:
sales_amounts.T

array([[12,  3,  9,  4,  1],
       [15,  3, 19,  6,  6],
       [ 0,  7, 18, 12,  7]])

In [9]:
prices.shape, sales_amounts.shape

((1, 3), (5, 3))

In [10]:
# Total Sales
total_sales = prices.dot(sales_amounts.T)
#total_sales = np.sum()
total_sales

array([[240, 138, 458, 232, 142]])

In [16]:
# create daily sales data frame
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.T

Price
Mon      240
Tue      138
Wed      458
Thurs    232
Fri      142

In [17]:
weekly_sales['Total ($)'] = daily_sales.T
weekly_sales

Almond butter  Peanut Butter  Cashew Butter  Total ($)
Mon               12             15              0        240
Tue                3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142